### ISSUE TITLE
File already exists issue for typescript version of hardhat

### ISSUE THREAD

**Issue by MichaelFedorov** [frangio/hardhat-exposed#36]
I used basic steps for hardhat installation with their simple project. It seems hardhat-expose doesn't work correctly for typescript version. I'm permanently getting an issue when running _npx hardhat compile --force_

Error: EEXIST: file already exists, mkdir '/Users/michaelfedorov/Documents/Blockchain/ERC20/contracts-exposed/ERC20.sol'
    at Object.mkdirSync (node:fs:1372:26)
    at mkdirpNativeSync (/Users/michaelfedorov/Documents/Blockchain/ERC20/node_modules/typechain/node_modules/mkdirp/lib/mkdirp-native.js:31:10)
    at mkdirpSync (/Users/michaelfedorov/Documents/Blockchain/ERC20/node_modules/typechain/node_modules/mkdirp/index.js:21:7)
    at /Users/michaelfedorov/Documents/Blockchain/ERC20/node_modules/typechain/src/typechain/io.ts:19:5
    at Array.forEach (<anonymous>)
    at processOutput (/Users/michaelfedorov/Documents/Blockchain/ERC20/node_modules/typechain/src/typechain/io.ts:17:13)
    at runTypeChain (/Users/michaelfedorov/Documents/Blockchain/ERC20/node_modules/typechain/src/typechain/runTypeChain.ts:57:36)
    at async SimpleTaskDefinition.action (/Users/michaelfedorov/Documents/Blockchain/ERC20/node_modules/@typechain/hardhat/src/index.ts:91:20)
    at async Environment._runTaskDefinition (/Users/michaelfedorov/Documents/Blockchain/ERC20/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async Environment.run (/Users/michaelfedorov/Documents/Blockchain/ERC20/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14) {
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/Users/michaelfedorov/Documents/Blockchain/ERC20/contracts-exposed/ERC20.sol'

**Comment by frangio** [comment]
Please share your Hardhat config. Are you using other plugins?

**Comment by ilyaa123** [comment]
hardhat.config.ts:
```typescript
import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import "hardhat-exposed";

const config: HardhatUserConfig = {
  solidity: "0.8.28",
};

export default config;
```

package.json:
```json
"devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^5.0.0",
    "hardhat": "^2.22.18",
    "hardhat-exposed": "^0.3.15"
 }
```

When running `hardhat compile --force` the following error occurs:
```
> compile
> hardhat compile --force

Generating typings for: 19 artifacts in dir: typechain-types for target: ethers-v6
An unexpected error occurred:

Error: EEXIST: file already exists, mkdir '/mnt/projects/demo-projects/solidity/books-solidity/contracts-exposed/Books.sol'
```
And, as I understand it, there is no typescript support?

**Comment by frangio** [comment]
> And, as I understand it, there is no typescript support?

This plugin hasn't been tested for TypeScript support.
